# Advanced NumPy

In [1]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
np.set_printoptions(precision=4)
import sys

## ndarray object internals

### NumPy dtype hierarchy

In [2]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)

True

In [5]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## Advanced array manipulation

### Reshaping arrays

In [4]:
arr = np.arange(8)
arr
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [6]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
other_arr = np.ones((3, 5))
other_arr.shape
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
arr = np.arange(15).reshape((5, 3))
arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### C vs. Fortran order

In [11]:
arr = np.arange(12).reshape((3, 4))
arr
arr.ravel()
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and splitting arrays

In [12]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [13]:
np.vstack((arr1, arr2))
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [14]:
from numpy.random import randn
arr = randn(5, 2)
arr
first, second, third = np.split(arr, [1, 3])
first
second
third

array([[ 2.5129,  0.427 ],
       [-0.344 ,  0.8173]])

#### Stacking helpers: 

In [15]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = randn(3, 2)
np.r_[arr1, arr2]
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [-1.3972,  1.4158,  3.    ],
       [-0.4665, -2.3625,  4.    ],
       [ 0.0622,  0.9707,  5.    ]])

In [16]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

### Repeating elements: tile and repeat

In [17]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [18]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [19]:
arr = randn(2, 2)
arr
arr.repeat(2, axis=0)

array([[ 0.9379,  1.0394],
       [ 0.9379,  1.0394],
       [-0.9499,  0.5795],
       [-0.9499,  0.5795]])

In [20]:
arr.repeat([2, 3], axis=0)
arr.repeat([2, 3], axis=1)

array([[ 0.9379,  0.9379,  1.0394,  1.0394,  1.0394],
       [-0.9499, -0.9499,  0.5795,  0.5795,  0.5795]])

In [21]:
arr
np.tile(arr, 2)

array([[ 0.9379,  1.0394,  0.9379,  1.0394],
       [-0.9499,  0.5795, -0.9499,  0.5795]])

In [22]:
arr
np.tile(arr, (2, 1))
np.tile(arr, (3, 2))

array([[ 0.9379,  1.0394,  0.9379,  1.0394],
       [-0.9499,  0.5795, -0.9499,  0.5795],
       [ 0.9379,  1.0394,  0.9379,  1.0394],
       [-0.9499,  0.5795, -0.9499,  0.5795],
       [ 0.9379,  1.0394,  0.9379,  1.0394],
       [-0.9499,  0.5795, -0.9499,  0.5795]])

### Fancy indexing equivalents: take and put

In [23]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [24]:
arr.take(inds)
arr.put(inds, 42)
arr
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [25]:
inds = [2, 0, 2, 1]
arr = randn(2, 4)
arr
arr.take(inds, axis=1)

array([[ 1.1614, -2.0327,  1.1614,  0.641 ],
       [ 0.6432, -1.3237,  0.6432,  0.3826]])

## Broadcasting

In [26]:
arr = np.arange(5)
arr
arr * 4

array([ 0,  4,  8, 12, 16])

In [27]:
arr = randn(4, 3)
arr.mean(0)
demeaned = arr - arr.mean(0)
demeaned
demeaned.mean(0)

array([ -5.5511e-17,   0.0000e+00,   0.0000e+00])

In [28]:
arr
row_means = arr.mean(1)
row_means.reshape((4, 1))
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([  0.0000e+00,  -7.4015e-17,   0.0000e+00,   0.0000e+00])

### Broadcasting over other axes

In [29]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [30]:
arr - arr.mean(1).reshape((4, 1))

array([[-0.1004,  0.5552, -0.4548],
       [ 0.1748,  0.5869, -0.7617],
       [ 0.2998,  0.5539, -0.8537],
       [ 0.0328,  1.1262, -1.159 ]])

In [31]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [32]:
arr_1d = np.random.normal(size=3)
arr_1d[:, np.newaxis]
arr_1d[np.newaxis, :]

array([[ 1.9868,  1.8891, -0.0676]])

In [ ]:
arr = randn(3, 4, 5)
depth_means = arr.mean(2)
depth_means
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

In [ ]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalized things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

### Setting array values by broadcasting

In [33]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [34]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

## Advanced ufunc usage

### Ufunc instance methods

In [35]:
arr = np.arange(10)
np.add.reduce(arr)
arr.sum()

45

In [36]:
np.random.seed(12346)

In [37]:
arr = randn(5, 5)
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [38]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [39]:
arr = np.arange(3).repeat([1, 2, 2])
arr
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [40]:
result = np.subtract.outer(randn(3, 4), randn(5))
result.shape

(3, 4, 5)

In [41]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [ ]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr
np.add.reduceat(arr, [0, 2, 4], axis=1)

### Custom ufuncs

In [ ]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

In [ ]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

In [ ]:
arr = randn(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

## Structured and record arrays

In [ ]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

In [ ]:
sarr[0]
sarr[0]['y']

In [ ]:
sarr['x']

### Nested dtypes and multidimensional fields

In [ ]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

In [ ]:
arr[0]['x']

In [ ]:
arr['x']

In [ ]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']
data['y']
data['x']['a']

### Why use structured arrays?

### Structured array manipulations: numpy.lib.recfunctions

## More about sorting

In [ ]:
arr = randn(6)
arr.sort()
arr

In [ ]:
arr = randn(3, 5)
arr
arr[:, 0].sort()  # Sort first column values in-place
arr

In [ ]:
arr = randn(5)
arr
np.sort(arr)
arr

In [ ]:
arr = randn(3, 5)
arr
arr.sort(axis=1)
arr

In [ ]:
arr[:, ::-1]

### Indirect sorts: argsort and lexsort

In [ ]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer
values[indexer]

In [ ]:
arr = randn(3, 5)
arr[0] = values
arr
arr[:, arr[0].argsort()]

In [ ]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

### Alternate sort algorithms

In [ ]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer
values.take(indexer)

### numpy.searchsorted: Finding elements in a sorted array

In [ ]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

In [ ]:
arr.searchsorted([0, 8, 11, 16])

In [ ]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])
arr.searchsorted([0, 1], side='right')

In [ ]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

In [ ]:
labels = bins.searchsorted(data)
labels

In [ ]:
Series(data).groupby(labels).mean()

In [ ]:
np.digitize(data, bins)

## NumPy matrix class

In [ ]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])
X[:, 0]  # one-dimensional
y = X[:, :1]  # two-dimensional by slicing
X
y

In [ ]:
np.dot(y.T, np.dot(X, y))

In [ ]:
Xm = np.matrix(X)
ym = Xm[:, 0]
Xm
ym
ym.T * Xm * ym

In [ ]:
Xm.I * X

## Advanced array input and output

### Memory-mapped files

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))
mmap

In [ ]:
section = mmap[:5]

In [ ]:
section[:] = np.random.randn(5, 10000)
mmap.flush()
mmap
del mmap

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

In [ ]:
%xdel mmap
!rm mymmap

### HDF5 and other array storage options

## Performance tips

### The importance of contiguous memory

In [ ]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
arr_c.flags
arr_f.flags
arr_f.flags.f_contiguous

In [ ]:
%timeit arr_c.sum(1)
%timeit arr_f.sum(1)

In [ ]:
arr_f.copy('C').flags

In [ ]:
arr_c[:50].flags.contiguous
arr_c[:, :50].flags

In [ ]:
%xdel arr_c
%xdel arr_f
%cd ..

## Other speed options: Cython, f2py, C

```cython
from numpy cimport ndarray, float64_t

def sum_elements(ndarray[float64_t] arr):
    cdef Py_ssize_t i, n = len(arr)
    cdef float64_t result = 0

    for i in range(n):
        result += arr[i]

    return result
```